### ISSUE TITLE
YelpCamp/routes/comments.js Ambiguous redirection

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/YelpCamp#14]
https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/routes/comments.js#L66-L73

Remove comment with stated **id**, and then redirect to the page with the comment with the same **id**? Will it still exist, if the comment has been removed?

**Comment by Jordan141** [comment]
id is the id of the campground that the comment is on, comment_id is the id of the comment itself, it redirects to the campground page where the comment was previously, to display the change.

**Comment by michaelKurowski** [comment]
Can't you name it `commentId`/`commentID`?

**Comment by Jordan141** [comment]
I can, I'll add it in next commit, since you're correct about the style.

**Comment by michaelKurowski** [comment]
Also, please name `.id`, `campgroundId`/`campgroundID` so it will be faster to spot.

**Comment by Jordan141** [comment]
I'll be renaming id to campgroundId and comment_id to commentId for sake of readability.
