### ISSUE TITLE
YelpCamp/app.js Ambigious code fragment

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/YelpCamp#21]
https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/app.js#L42-L48

How does it checks anything? I don't see any conditionals. Could you make the code snippet a little bit more easier to understand?

**Comment by Jordan141** [comment]
Good catch I'll sort that
