### ISSUE TITLE
YelpCamp/routes/index.js unelegant console.log

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/YelpCamp#3]
https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/routes/index.js#L17

Do not use console.log to output errors. Use specialized library, or make your own error logging system. Preferably, throw errors to files too.

**Comment by Jordan141** [comment]
Fixed three years ago, app currently uses flashcards for errors, I'll be opening an issue to replace these as the user should not see errors.
