### ISSUE TITLE
YelpCamp/routes/index.js delcarative style authentication

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/YelpCamp#4]
https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/routes/index.js#L20

Can't you use declarative style authentication, like in router.post('/login', ... ?

**Comment by Jordan141** [comment]
Can you elaborate?

**Comment by michaelKurowski** [comment]
https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/routes/index.js#L20-L22

https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/routes/index.js#L30-L36

The second way of using `passport.authenticate`, looks far more readable, cuz of being declarative.

**Comment by Jordan141** [comment]
Fixed in recent commit
