### ISSUE TITLE
YelpCamp/routes/index.js Empty function takes arguments

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/YelpCamp#5]
https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/routes/index.js#L34-L36
Why does this empty function accepts arguments? Also, please get rid of this meaningless free line below

**Comment by Jordan141** [comment]
Thanks for picking this up, this is something I meant to come back to
