### ISSUE TITLE
YelpCamp/routes/index.js space after comma

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/YelpCamp#6]
https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/routes/index.js#L27

I'd suggest to use CI with linter. It will prevent such things. You don't need to run linter every time, just make it block wrongly styled pushes. Please lint your whole code, because I've noticed that you have a lot of similar issues in whole app.

**Comment by Jordan141** [comment]
Solved
