### ISSUE TITLE
YelpCamp/routes/comments.js Avoid abbreviation

### ISSUE THREAD

**Issue by michaelKurowski** [Jordan141/YelpCamp#8]
https://github.com/Jordan141/YelpCamp/blob/d997d2227bfd59484fc9c1f8aa8b98aafa3ccc5d/routes/comments.js#L10

Get rid of `cg` argument.
It's better to scroll through long-named variables with obvious meaning, than to need to find out what every abbreviation means.

**Comment by Jordan141** [comment]
Already fixed
